version: 2.1

jobs:

  tests: &test-template
    parameters:
      pyver:
        default: "13"
        type: string
    description: Tests - Python 3.<<parameters.pyver>>
    docker:
      - image: python:3.<<parameters.pyver>>
    resource_class: small
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox

  quality:
    <<: *test-template
    description: Code style - Python 3.<<parameters.pyver>>
    environment:
      TOXENV: style

  online:
    <<: *test-template
    description: Tests online - Python 3.<<parameters.pyver>>
    environment:
      TOXENV: online

  images:
    <<: *test-template
    description: Tests images - Python 3.<<parameters.pyver>>
    environment:
      TOXENV: images
    steps:
      - checkout
      - run:
          name: Install OpenGL deps
          command: |
            apt-get update
            apt-get install -y --no-install-recommends \
              libgl1 libglx-mesa0 libgl1-mesa-dri libegl1-mesa-dev libgles2-mesa-dev libosmesa6 xvfb xauth
      - run: python -m pip install tox
      - run: xvfb-run -a tox

  coverage:
    <<: *test-template
    description: Tests coverage - Python 3.<<parameters.pyver>>
    environment:
      TOXENV: coverage
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox
      - run: python -m pip install codecov && codecov

  preversion:
    <<: *test-template
    description: Tests with preversion packages - Python 3.<<parameters.pyver>>
    environment:
      TOXENV: fast
    steps:
      - checkout
      - run: python -m pip install tox
      - run: python -m pip install --pre --upgrade --no-deps astropy
      - run: python -m pip install --pre --upgrade --no-deps numpy
      - run: python -m pip install --pre --upgrade --no-deps numba
      - run: python -m pip install --pre --upgrade --no-deps scipy
      - run: tox


workflows:
  build_and_test:
    jobs:
      - quality
      - tests:
          matrix:
            parameters:
              pyver:
                - "10"
                - "11"
                - "12"
                - "13"
                - "14"
          requires:
            - quality
      - online:
          requires:
            - tests
      - images:
          requires:
            - tests
      - coverage:
          requires:
            - tests
      - preversion:
          pyver: "14"
          requires:
            - tests
